services:
  - type: web
    name: prova-sdr
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RESULT_RECIPIENT_EMAIL
        value: rodrigo.melo@totallpi.co
      - key: MS_GRAPH_SENDER
        value: rodrigo.melo@totallpi.co
      - key: MS_GRAPH_TENANT_ID
        sync: false
      - key: MS_GRAPH_CLIENT_ID
        sync: false
      - key: MS_GRAPH_CLIENT_SECRET
        sync: false
